# Generated by Django 3.2.8 on 2021-12-11 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0021_auto_20211205_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('bought_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='base.profile')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='base.profile')),
            ],
        ),
    ]
