# Generated by Django 3.2.8 on 2021-12-11 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerView', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 11, 18, 37, 7, 569763)),
        ),
    ]
