# Generated by Django 3.2.8 on 2021-12-11 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerView', '0003_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 11, 20, 55, 2, 527739)),
        ),
    ]
