# Generated by Django 3.2.8 on 2021-12-11 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerView', '0004_auto_20211211_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 11, 23, 5, 41, 608388)),
        ),
    ]
