# Generated by Django 3.2.8 on 2021-12-11 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerView', '0005_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 11, 23, 13, 19, 238317)),
        ),
    ]
