# Generated by Django 3.2.8 on 2021-11-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_photo'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_in_rupees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
