# Generated by Django 3.2.8 on 2021-12-05 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_productimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default=uuid.UUID('dba54b9c-4bb2-4b9e-8704-a6c37838b9ef'), max_length=100, null=True, unique=True),
        ),
    ]
