# Generated by Django 3.2.8 on 2021-12-05 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default=uuid.UUID('9bb3ca79-4892-442c-8be9-6b3247e1a415'), max_length=100, null=True, unique=True),
        ),
    ]
