# Generated by Django 3.2.8 on 2021-12-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20211205_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_verified',
            new_name='is_sold',
        ),
    ]
